packages:
  - packages/core
  - packages/reader
  - packages/sqlite-browser

catalog:
  "@biomejs/biome": ^1.9.4
  "@types/bun": latest
  "@types/node": ^22.10.2
  "@vitest/browser": ^3.1.4
  playwright: ^1.54.1
  typescript: ^5.0.0
  vite: ^6.0.0
  vite-plugin-node-polyfills: ^0.23.0
  vitest: ^3.1.4